apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "iqserver.fullname" . }}-conf
  labels: {{ include "iqserver.labels" . | nindent 4 }}
data:
  config.yml: |
{{ toYaml .Values.configYaml | indent 4 }}
