{{- if .Values.nexus.properties.override -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nexus.name" . }}-properties
  labels: {{ include "nexus.labels" . | nindent 4 }}
data:
  nexus.properties: |
    {{- range $k, $v := .Values.nexus.properties.data }}
    {{ $k }}={{ $v }}
    {{- end }}
{{- end }}