{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nexus.name" . }}-conf
  labels: {{ include "nexus.labels" . | nindent 4 }}
data:
{{ toYaml .Values.config.data | indent 2 }}
{{- end }}