{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}-secret
  labels: {{ include "nexus.labels" . | nindent 4 }}
data:
{{ toYaml .Values.secret.data | indent 2 }}
{{- end}}
